### ISSUE TITLE
 A way to crash the editor with 2/3 blocks. 

### ISSUE THREAD

**Issue by colinator27** [SharpScratchMod/Sharp#7]
Putting a forever loop around the GET block or the notify block lags the editor greatly, eventually leading to its crash after a few minutes. During this time, the editor is extremely hard to operate.

I would suggest either putting a limit on how many times the blocks' actions can occur (it's possible, I've done it before on my personal mod) or letting them fire once at a time. (waiting block)

**Comment by edward789121** [comment]
Fire once a time.

**Comment by ghost** [comment]
Oh my. we'll see what we can do for now

**Comment by Mrcomputer1** [comment]
Fixed in b33fb27
Only 10 HTTP request can be active at one time
Only 10 dialog boxes (created with notify block) can be active at one time

Only one medium problem: If you go over the limit then the block will not run and will be ignored
Another smaller problem: If a HTTP request fails that block will not be removed from the running HTTP request count
